# Generated by Django 3.1.2 on 2020-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='email',
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='first', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='last', max_length=100),
            preserve_default=False,
        ),
    ]
