# Generated by Django 3.1.2 on 2020-10-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201006_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
